<?php
//$Id$
/**
 * @file
 *
 * Override 'me' aliases functionality.
 */

/**
 * Implementation of hook_menu_alter
 * @param Array $items
 */
function supportgroups_me_menu_alter(&$items) {
  // Override me module overrides for relationship links
  $links = user_relationships_ui_menu();
  foreach ($links as $path => $link) {
    $items[$path] = $link;
    $items[$path]['file path'] = drupal_get_path('module', 'user_relationships_ui');
  }
}

/**
 * Implements hook_form_form_id_alter().
 */
function supportgroups_me_form_user_register_form_alter(&$form, $form_state) {
  $form['terms_of_use']['#weight'] = 9;
}