<?php

$questions = array(
	'1'  => array( 'title' => 'Am the life of the party.',						'category' => '1', 'type' => '+'),
	'2'  => array( 'title' => 'Feel little concern for others.',				'category' => '2', 'type' => '-'),
	'3'  => array( 'title' => 'Am always prepared.',							'category' => '3', 'type' => '+'),
	'4'  => array( 'title' => 'Get stressed out easily.',						'category' => '4', 'type' => '-'),
	'5'  => array( 'title' => 'Have a rich vocabulary. ',						'category' => '5', 'type' => '+'),
	'6'  => array( 'title' => 'Do not talk a lot.',								'category' => '1', 'type' => '-'),
	'7'  => array( 'title' => 'Am interested in people. ',						'category' => '2', 'type' => '+'),
	'8'  => array( 'title' => 'Leave my belongings around.',					'category' => '3', 'type' => '-'),
	'9'  => array( 'title' => 'Am relaxed most of the time.',					'category' => '4', 'type' => '+'),
	'10' => array( 'title' => 'Have difficulty understanding abstract ideas.',	'category' => '5', 'type' => '-'),
	'11'  => array( 'title' => 'Feel comfortable around people.',				'category' => '1', 'type' => '+'),
	'12'  => array( 'title' => 'Insult people. ',								'category' => '2', 'type' => '-'),
	'13'  => array( 'title' => 'Pay attention to details.',						'category' => '3', 'type' => '+'),
	'14'  => array( 'title' => 'Worry about things.',							'category' => '4', 'type' => '-'),
	'15' => array( 'title' => 'Have a vivid imagination.',						'category' => '5', 'type' => '+'),
	'16'  => array( 'title' => 'Keep in the background.',						'category' => '1', 'type' => '-'),
	'17'  => array( 'title' => 'Sympathize with the feelings of others. ',		'category' => '2', 'type' => '+'),
	'18'  => array( 'title' => 'Make a mess of things.',						'category' => '3', 'type' => '-'),
	'19'  => array( 'title' => 'Seldom feel blue.',								'category' => '4', 'type' => '+'),
	'20' => array( 'title' => 'Am not interested in abstract ideas.',			'category' => '5', 'type' => '-'),
	'21'  => array( 'title' => 'Start conversations.',							'category' => '1', 'type' => '+'),
	'22'  => array( 'title' => 'Am not interested in the problems of others. ',	'category' => '2', 'type' => '-'),
	'23'  => array( 'title' => 'Get chores done right away.',					'category' => '3', 'type' => '+'),
	'24'  => array( 'title' => 'Am easily disturbed.',							'category' => '4', 'type' => '-'),
	'25' => array( 'title' => 'Have excellent ideas.',							'category' => '5', 'type' => '+'),
	'26'  => array( 'title' => 'Have little to say.',							'category' => '1', 'type' => '-'),
	'27'  => array( 'title' => 'Have a soft heart. ',							'category' => '2', 'type' => '+'),
	'28'  => array( 'title' => 'Often forget to put things back in their proper place.',	'category' => '3', 'type' => '-'),
	'29'  => array( 'title' => 'Get upset easily.',								'category' => '4', 'type' => '-'),
	'30' => array( 'title' => 'Do not have a good imagination.',				'category' => '5', 'type' => '-'),
	'31'  => array( 'title' => 'Talk to a lot of different people at parties.',	'category' => '1', 'type' => '+'),
	'32'  => array( 'title' => 'Am not really interested in others. ',			'category' => '2', 'type' => '-'),
	'33'  => array( 'title' => 'Like order.',									'category' => '3', 'type' => '+'),
	'34'  => array( 'title' => 'Change my mood a lot.',							'category' => '4', 'type' => '-'),
	'35' => array( 'title' => 'Am quick to understand things.',					'category' => '5', 'type' => '+'),
	'36'  => array( 'title' => 'Do not like to draw attention to myself.',		'category' => '1', 'type' => '-'),
	'37'  => array( 'title' => 'Take time out for others. ',					'category' => '2', 'type' => '+'),
	'38'  => array( 'title' => 'Avoid my duties.',								'category' => '3', 'type' => '-'),
	'39'  => array( 'title' => 'Have frequent mood swings.',					'category' => '4', 'type' => '-'),
	'40' => array( 'title' => 'Use difficult words.',							'category' => '5', 'type' => '+'),
	'41'  => array( 'title' => 'Do not mind being the center of attention.',	'category' => '1', 'type' => '+'),
	'42'  => array( 'title' => 'Feel the emotions of others. ',					'category' => '2', 'type' => '+'),
	'43'  => array( 'title' => 'Follow a schedule.',							'category' => '3', 'type' => '+'),
	'44'  => array( 'title' => 'Get irritated easily.',							'category' => '4', 'type' => '-'),
	'45' => array( 'title' => 'Spend time reflecting on things.',				'category' => '5', 'type' => '+'),
	'46'  => array( 'title' => 'Am quiet around strangers.',					'category' => '1', 'type' => '-'),
	'47'  => array( 'title' => 'Make people feel at ease. ',					'category' => '2', 'type' => '+'),
	'48'  => array( 'title' => 'Am exacting in my work.',						'category' => '3', 'type' => '+'),
	'49'  => array( 'title' => 'Often feel blue.',								'category' => '4', 'type' => '-'),
	'50' => array( 'title' => 'Am full of ideas.',								'category' => '5', 'type' => '+')
	);
