<?php

/**
 *  This function will return the list of groups 
 *
 */
function supportgroups_taxonomy_group_array(){

$groupOptions = array(

  // Start of item
  // Id of the group
  29162 => array(
    'title' => 'Abuse',
    'nid' => 29162,
    // Add the groups related to the parent group
    'taxonomy' => array(
    // The numbers on the right are the number of groups associated with the parent group
// alway start with 0
      0 => array(
        // title of group
        'title' => 'Anxiety',
        // id of group
        'nid' => 29168
      ),
      1 => array(
        'title' => 'Bullying',
        'nid' => 31453
      ),
      2 => array(
        'title' => 'Depression',
        'nid' => 29176
      ),
      3 => array(
        'title' => 'Divorce',
        'nid' => 29178
      ),
      4 => array(
        'title' => 'Emotional Abuse',
        'nid' => 35205
      ),
      5 => array(
        'title' => 'Family',
        'nid' => 29180
      ),
    // beginning of last item
      6 => array(
        'title' => 'Relationship',
        'nid' => 29199
      ),
      //end of last item//
    )
  ),
  // End of Item
  
  // Start of Item
  29163 => array(
    'title' => 'Acne',
    'nid' => 29163,
    'taxonomy' => array(
      0 => array(
        'title' => 'Anxiety',
        'nid' => 29168
      ), 
      1 => array(
        'title' => 'Depression',
        'nid' => 29176
      ), 
      2 => array(
        'title' => 'Stress',
        'nid' => 29206
      ), 
      3 => array(
        'title' => 'Food Allergy',
        'nid' => 29183
      ), 
      4 => array(
        'title' => 'College',
        'nid' => 29175
      ), 
      5 => array(
        'title' => 'Teen',
        'nid' => 31954
      ), 
   6 => array(
        'title' => 'Bullying',
        'nid' => 31453
      ), 
   7 => array(
        'title' => 'Self Esteem',
        'nid' => 29932
      ), 
    )
  ),
  // End of Item


// Start of item
 // Id of the group
 37215 => array(
   'title' => 'Adderall',
   'nid' => 37215,
    'taxonomy' => array(
        0 => array(
        'title' => 'ADHD',
        'nid' => 29164
     ),
     1 => array(
       'title' => 'Anxiety',
       'nid' => 29168
     ),
     2 => array(
       'title' => 'Prescription Drug',
       'nid' => 29196
     ),
    3 => array(
       'title' => 'Drug',
       'nid' => 29027
     ),
    4 => array(
       'title' => 'College',
       'nid' => 29175
     ),
    5 => array(
       'title' => 'Teen',
       'nid' => 31954
     ),
    6 => array(
       'title' => 'Stress',
       'nid' => 29206
     ),
    7 => array(
       'title' => 'Depression',
       'nid' => 29176
     ),

    )
  ),
  // End of Item


// Start of item
// Id of the group
29164 => array(
  'title' => 'ADHD',
  'nid' => 29164,
   'taxonomy' => array(
       0 => array(
       'title' => 'Adderall',
      'nid' => 37215
    ),
    1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
    2 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
   3 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
   4 => array(
      'title' => 'College',
      'nid' => 29175
    ),
   5 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
   6 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   7 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),


   )
 ),
 // End of Item


// Start of item
// Id of the group
31434 => array(
  'title' => 'Adoption',
  'nid' => 31434,
   'taxonomy' => array(
       0 => array(
       'title' => 'Family',
      'nid' => 29180
    ),
    1 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
    2 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
   3 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
   4 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   5 => array(
      'title' => 'Siblings',
      'nid' => 29204
    ),
   6 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
35204 => array(
  'title' => 'Agoraphobia',
  'nid' => 35204,
   'taxonomy' => array(
       0 => array(
       'title' => 'Anxiety',
      'nid' => 29168
    ),
    1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
    2 => array(
      'title' => 'Panick Attack',
      'nid' => 29890
    ),
   3 => array(
      'title' => 'Phobia',
      'nid' => 29922
    ),
   4 => array(
      'title' => 'Shyness',
      'nid' => 40264
    ),
   5 => array(
      'title' => 'Social Anxiety',
      'nid' => 29168
    ),
   
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
29165 => array(
  'title' => 'Alcohol',
  'nid' => 29165,
   'taxonomy' => array(
       0 => array(
       'title' => 'Anxiety',
      'nid' => 29168
    ),
/* TODO FIX WRONG TITLE */
    1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
    2 => array(
      'title' => 'Cirrhosis',
      'nid' => 35232
    ),
   3 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
   4 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
   5 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
      6 => array(
      'title' => 'Social Anxiety',
      'nid' => 52264
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
31449 => array(
  'title' => 'Alzheimers',
  'nid' => 31449,
   'taxonomy' => array(
       0 => array(
       'title' => 'Dementia',
      'nid' => 44592
    ),
    1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
    2 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
   3 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   4 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
37216 => array(
  'title' => 'Ambien',
  'nid' => 37216,
   'taxonomy' => array(
       0 => array(
       'title' => 'Prescription Drug',
      'nid' => 29196
    ),
    1 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
    2 => array(
      'title' => 'Sleep Walking',
      'nid' => 52266
    ),
   3 => array(
      'title' => 'Insomnia',
      'nid' => 29192
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
47191 => array(
  'title' => 'Amputee',
  'nid' => 47191,
   'taxonomy' => array(
       0 => array(
       'title' => 'Depression',
       'nid' => 29176
    ),
    1 => array(
      'title' => 'Veterans',
      'nid' => 52262
    ),
    2 => array(
      'title' => 'Diabetes',
      'nid' => 29177
    ),
   3 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
   4 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
   5 => array(
      'title' => 'Military Family',
      'nid' => 31436
    ),
      6 => array(
      'title' => 'War and Terrorism',
      'nid' => 31448
    ),
 
   )
 ),
 // End of Item
 

// Start of item
// Id of the group
37212 => array(
  'title' => 'Anemia',
  'nid' => 37212,
   'taxonomy' => array(
       0 => array(
       'title' => 'Dizziness',
      'nid' => 31452
    ),
    1 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
    2 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
  
   )
 ),
 // End of Item
 
// Start of item
// Id of the group
29166 => array(
  'title' => 'Anger Management',
  'nid' => 29166,
   'taxonomy' => array(
       0 => array(
       'title' => 'Abuse',
        'nid' => 29162
    ),
    1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
    2 => array(
      'title' => 'Alcohol',
      'nid' => 29165
    ),
   3 => array(
      'title' => 'Emotional Abuse',
      'nid' => 35205
    ),
   4 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
   5 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
  
   )
 ),
 // End of Item
 
// Start of item
// Id of the group
29167 => array(
  'title' => 'Anorexia',
  'nid' => 29167,
   'taxonomy' => array(
       0 => array(
       'title' => 'Bulimia',
        'nid' => 29174
    ),
    1 => array(
      'title' => 'Eating Disorder',
      'nid' => 29179
    ),
    2 => array(
      'title' => 'EDNOS',
      'nid' => 38499
    ),
   3 => array(
      'title' => 'Exercise Addiction',
      'nid' => 40263
    ),
   4 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
   5 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
      6 => array(
      'title' => 'College',
      'nid' => 29175
    ),
  7 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
   8 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),
  9 => array(
      'title' => 'Body Dismporphic Disorder',
      'nid' => 40267
    ),
10 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
11 => array(
      'title' => 'Binge Eating',
      'nid' => 29170
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
29168 => array(
  'title' => 'Anxiety',
  'nid' => 29168,
   'taxonomy' => array(
       0 => array(
       'title' => 'College',
      'nid' => 29175
    ),
    1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
    2 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
   3 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
   4 => array(
      'title' => 'OCD',
      'nid' => 29194
    ),
   5 => array(
      'title' => 'Panic Attack',
      'nid' => 29890
    ),
      6 => array(
      'title' => 'Phobia',
      'nid' => 29922
    ),
  7 => array(
      'title' => 'PTSD',
      'nid' => 29198
    ),
   8 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  9 => array(
      'title' => 'Social Anxiety',
      'nid' => 29168
    ),
10 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),

   )
 ),
 // End of Item
 

 // Start of item
// Id of the group
29918 => array(
  'title' => 'Arthritis',
  'nid' => 29918,
   'taxonomy' => array(
       0 => array(
       'title' => 'Medicare',
      'nid' => 47183
    ),
    1 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
    2 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
   3 => array(
      'title' => 'Social Security',
      'nid' => 52263
    ),
   4 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  
   )
 ),
 // End of Item
 

// Start of item
// Id of the group
31429 => array(
  'title' => 'Asperger Syndrome',
  'nid' => 31429,
   'taxonomy' => array(
       0 => array(
       'title' => 'Autism',
      'nid' => 29169
    ),
    1 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
    2 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
   3 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
29909 => array(
  'title' => 'Asthma',
  'nid' => 29909,
   'taxonomy' => array(
       0 => array(
       'title' => 'COPD',
      'nid' => 31437
    ),
    1 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
    2 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
   3 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   4 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
   5 => array(
      'title' => 'Smoking',
      'nid' => 29205
    ),
     
   )
 ),
 // End of Item


// Start of item
// Id of the group
37217 => array(
  'title' => 'Ativan',
  'nid' => 37217,
   'taxonomy' => array(
       0 => array(
       'title' => 'Anxiety',
      'nid' => 29168
    ),
    1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
    2 => array(
      'title' => 'Insomnia',
      'nid' => 29192
    ),
   3 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   4 => array(
      'title' => 'Prescription Drugs',
      'nid' => 29196
    ),
   5 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
      6 => array(
      'title' => 'Xanax',
      'nid' => 37233
    ),
  7 => array(
      'title' => 'Panic Attack',
      'nid' => 29890
    ),
   8 => array(
      'title' => 'Social Anxiety',
      'nid' => 29168
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
29169 => array(
  'title' => 'Autism',
  'nid' => 29169,
   'taxonomy' => array(
       0 => array(
       'title' => 'Asperger Syndrome',
      'nid' => 31429
    ),
    1 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
    2 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   3 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
   4 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
31426 => array(
  'title' => 'Back Pain',
  'nid' => 31426,
   'taxonomy' => array(
       0 => array(
       'title' => 'Chronic Pain',
      'nid' => 29901
    ),
    1 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
    2 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   3 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
   4 => array(
      'title' => 'Vicodin',
      'nid' => 37246
    ),
   5 => array(
      'title' => 'Surgery',
      'nid' => 31632
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
44611 => array(
  'title' => 'Bedwetting',
  'nid' => 44611,
   'taxonomy' => array(
       0 => array(
       'title' => 'Parents',
      'nid' => 29195
    ),
    1 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
    2 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29170 => array(
  'title' => 'Binge Eating',
  'nid' => 29170,
   'taxonomy' => array(
       0 => array(
       'title' => 'Anorexia',
      'nid' => 29167
    ),
    1 => array(
      'title' => 'Bulimia',
      'nid' => 29174
    ),
    2 => array(
      'title' => 'Eating Disorder',
      'nid' => 29179
    ),
   3 => array(
      'title' => 'EDNOS',
      'nid' => 38499
    ),
   4 => array(
      'title' => 'Exercise Addiction',
      'nid' => 40263
    ),
   5 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
      6 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
  7 => array(
      'title' => 'College',
      'nid' => 29175
    ),
   8 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  9 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),
10 => array(
      'title' => 'Body Dysmorphic Disorder',
      'nid' => 40267
    ),
11 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
29171 => array(
  'title' => 'Bipolar',
  'nid' => 29171,
   'taxonomy' => array(
       0 => array(
       'title' => 'Depression',
      'nid' => 29176
    ),
    1 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
    2 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
   3 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   4 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   5 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
      6 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
  7 => array(
      'title' => 'College',
      'nid' => 29175
    ),
   8 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
  9 => array(
      'title' => 'Seroquel',
      'nid' => 37229
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
64791 => array(
  'title' => 'Birth Defects',
  'nid' => 64791,
   'taxonomy' => array(
       0 => array(
       'title' => 'Parents',
      'nid' => 29195
    ),
    1 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
    2 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
31427 => array(
  'title' => 'Bisexuality',
  'nid' => 31427,
   'taxonomy' => array(
       0 => array(
       'title' => 'Coming Out',
      'nid' => 47181
    ),
    1 => array(
      'title' => 'Gay and Lesbian',
      'nid' => 29186
    ),
    2 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
   3 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
35212 => array(
  'title' => 'Bladder Cancer',
  'nid' => 35212,
   'taxonomy' => array(
       0 => array(
       'title' => 'Chemotherapy',
      'nid' => 37247
    ),
    1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
    2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   3 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
40267 => array(
  'title' => 'Body Dysmorphic Disorder',
  'nid' => 40267,
   'taxonomy' => array(
       0 => array(
       'title' => 'Binge Eating',
      'nid' => 29170
    ),
    1 => array(
      'title' => 'Anorexia',
      'nid' => 29167
    ),
    2 => array(
      'title' => 'Bulimia',
      'nid' => 29174
    ),
   3 => array(
      'title' => 'Eating Disorder',
      'nid' => 29179
    ),
   4 => array(
      'title' => 'EDNOS',
      'nid' => 38499
    ),
   5 => array(
      'title' => 'Exercise Addiction',
      'nid' => 40263
    ),
      6 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
  7 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
   8 => array(
      'title' => 'College',
      'nid' => 29175
    ),
  9 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  10 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),
  11 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
35214 => array(
  'title' => 'Bone Cancer',
  'nid' => 35214,
   'taxonomy' => array(
       0 => array(
       'title' => 'Chemotherapy',
      'nid' => 37247
    ),
    1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
    2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   3 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
29172 => array(
  'title' => 'Borderline Personality Disorder',
  'nid' => 29172,
   'taxonomy' => array(
       0 => array(
       'title' => 'Depression',
      'nid' => 29176
    ),
    1 => array(
      'title' => 'Friends and Family of BPD',
      'nid' => 102839
    ),
    2 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
   3 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
35215 => array(
  'title' => 'Brain Cancer',
  'nid' => 35215,
   'taxonomy' => array(
       0 => array(
       'title' => 'Chemotherapy',
      'nid' => 37247
    ),
    1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
    2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   3 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
30721=> array(
  'title' => 'Brain Injury',
  'nid' => 30721,
   'taxonomy' => array(
       0 => array(
       'title' => 'Medicare',
      'nid' => 47183
    ),
    1 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
    2 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
   3 => array(
      'title' => 'Veterans',
      'nid' => 52262
    ),
   4 => array(
      'title' => 'War and Terroism',
      'nid' => 31448
    ),
   5 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
     
   )
 ),
 // End of Item


// Start of item
// Id of the group
29173 => array(
  'title' => 'Breast Cancer',
  'nid' => 29173,
   'taxonomy' => array(
       0 => array(
       'title' => 'Chemotherapy',
      'nid' => 37247
       ),
   1 => array(
       'title' => 'Medicare',
      'nid' => 47183
    ),
    2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
    3 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
   4 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
        
   )
 ),
 // End of Item


// Start of item
// Id of the group
44598 => array(
  'title' => 'Breastfeeding',
  'nid' => 44598,
   'taxonomy' => array(
       0 => array(
       'title' => 'Moms',
      'nid' => 31952
       ),
   1 => array(
       'title' => 'Parents',
      'nid' => 29195
    ),
    2 => array(
      'title' => 'Pregnancy',
      'nid' => 29903
    ),
    3 => array(
      'title' => 'Single Moms',
      'nid' => 44610
    ),
      
   )
 ),
 // End of Item


// Start of item
// Id of the group
29174 => array(
  'title' => 'Bulimia',
  'nid' => 29174,
   'taxonomy' => array(
       0 => array(
       'title' => 'Body Dysmorphic Disorder',
      'nid' => 40267
       ),
   1 => array(
       'title' => 'Binge Eating',
      'nid' => 29170
    ),
    2 => array(
      'title' => 'Anorexia',
      'nid' => 29167
    ),
    3 => array(
      'title' => 'Eating Disorder',
      'nid' => 29179
    ),
   4 => array(
      'title' => 'EDNOS',
      'nid' => 38499
    ),
   5 => array(
      'title' => 'Exercise Addiction',
      'nid' => 40263
    ),
   6 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
      7 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
  8 => array(
      'title' => 'College',
      'nid' => 29175
    ),
   9 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
10 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),
11 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
31453 => array(
  'title' => 'Bullying',
  'nid' => 31453,
   'taxonomy' => array(
       0 => array(
       'title' => 'Parents',
      'nid' => 29195
       ),
   1 => array(
       'title' => 'Moms',
      'nid' => 31952
    ),
    2 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
    3 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
   4 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   5 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
   6 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
      7 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
  8 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   9 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
45937 => array(
  'title' => 'Burn',
  'nid' => 45937,
   'taxonomy' => array(
       0 => array(
       'title' => 'Chronic Pain',
      'nid' => 29901
       ),
   1 => array(
       'title' => 'Drug',
      'nid' => 29027
    ),
    2 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
    3 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
   4 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   5 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   6 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
    
   )
 ),
 // End of Item


// Start of item
// Id of the group
35235 => array(
  'title' => 'Caffeine',
  'nid' => 352357,
   'taxonomy' => array(
       0 => array(
       'title' => 'Insomnia',
      'nid' => 29192
       ),
   1 => array(
       'title' => 'Stress',
      'nid' => 29206
    ),
    2 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
      
   )
 ),
 // End of Item


// Start of item
// Id of the group
44600 => array(
  'title' => 'Career Changes',
  'nid' => 44600,
   'taxonomy' => array(
       0 => array(
       'title' => 'Unemployment',
      'nid' => 31082
       ),
   1 => array(
       'title' => 'Financial Problems',
      'nid' => 29182
    ),
    2 => array(
      'title' => 'Depression',
      'nid' => 29168
    ),
    3 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   4 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
44622 => array(
  'title' => 'Caregivers',
  'nid' => 44622,
   'taxonomy' => array(
       0 => array(
       'title' => 'Parents',
      'nid' => 29195
       ),
   1 => array(
       'title' => 'Family',
      'nid' => 29180
    ),
    2 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
    3 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   4 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   5 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
  6 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
   7 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
44602 => array(
  'title' => 'Carpal Tunnel Syndrome',
  'nid' => 44602,
   'taxonomy' => array(
       0 => array(
       'title' => 'Chronic Pain',
      'nid' => 29901
       ),
  
   )
 ),
 // End of Item
// Start of item
// Id of the group
31443 => array(
  'title' => 'Celiac Disease',
  'nid' => 31443,
   'taxonomy' => array(
       0 => array(
       'title' => 'Healthy Eating',
      'nid' => 35227
       ),
   1 => array(
       'title' => 'Nutrition',
      'nid' => 44613
    ),
    2 => array(
      'title' => 'Food Allergy',
      'nid' => 29183
    ),
    
   )
 ),
 // End of Item


// Start of item
// Id of the group
31445 => array(
  'title' => 'Cerebral Palsy',
  'nid' => 31445,
   'taxonomy' => array(
       0 => array(
       'title' => 'Parents',
      'nid' => 29195
       ),
   1 => array(
       'title' => 'Moms',
      'nid' => 31952
    ),
    2 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
    3 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
   4 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   5 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
35216 => array(
  'title' => 'Cervical Cancer',
  'nid' => 35216,
   'taxonomy' => array(
       0 => array(
       'title' => 'HPV',
      'nid' => 31442
       ),
   1 => array(
       'title' => 'Chemotherapy',
      'nid' => 37247
    ),
   2 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   3 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   4 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
37240 => array(
  'title' => 'Chantix',
  'nid' => 37240,
   'taxonomy' => array(
       0 => array(
       'title' => 'Smoking',
      'nid' => 29205
       ),
   
   )
 ),
 // End of Item



// Start of item
// Id of the group
37247 => array(
  'title' => 'Chemotherapy',
  'nid' => 37247,
   'taxonomy' => array(
  0 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   1 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   2 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
   3 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  4 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
29911 => array(
  'title' => 'Chronic Fatigue Syndrome',
  'nid' => 29911,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   3 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  4 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29901 => array(
  'title' => 'Chronic Pain',
  'nid' => 29901,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chronic Fatigue Syndrome',
      'nid' => 29911
    ),
  1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   3 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  4 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
   5 => array(
      'title' => 'Fibromyalgia',
      'nid' => 29181
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
35232 => array(
  'title' => 'Cirrhosis',
  'nid' => 35232,
   'taxonomy' => array(
  0 => array(
      'title' => 'Alcohol',
      'nid' => 29165
    ),
  1 => array(
      'title' => 'Hepatitis C',
      'nid' => 35226
    ),
   2 => array(
      'title' => 'Diabetes',
      'nid' => 29177
    ),
   3 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),
  4 => array(
      'title' => 'Cystic Fibrosis',
      'nid' => 44599
    ),
   5 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
35208 => array(
  'title' => 'Cocaine',
  'nid' => 35208,
   'taxonomy' => array(
  0 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
  1 => array(
      'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
29905 => array(
  'title' => 'Codependency',
  'nid' => 29905,
   'taxonomy' => array(
  0 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
  1 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
   2 => array(
      'title' => 'Siblings',
      'nid' => 57786
    ),
   3 => array(
      'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  4 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
   5 => array(
      'title' => 'Alcohol',
      'nid' => 29165
    ),

   )
 ),
 // End of Item
// Start of item
// Id of the group
29175 => array(
  'title' => 'College',
  'nid' => 29175,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
   2 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   3 => array(
      'title' => 'Eating Disorder',
      'nid' => 29179
    ),
  4 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
   5 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
  6 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
   7 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),
   8 => array(
      'title' => 'Alcohol ',
      'nid' => 29165
    ),
  9 => array(
      'title' => 'Adderall ',
      'nid' => 37215
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
29926 => array(
  'title' => 'Colon Cancer',
  'nid' => 29926,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   3 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
35217 => array(
  'title' => 'Colorectal Cancer',
  'nid' => 35217,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   3 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
47181 => array(
  'title' => 'Coming Out',
  'nid' => 47181,
   'taxonomy' => array(
  0 => array(
      'title' => 'Bisexual',
      'nid' => 31427
    ),
  1 => array(
      'title' => 'Gay and Lesbian',
      'nid' => 29186
    ),
   2 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
   3 => array(
      'title' => 'College',
      'nid' => 29175
    ),
  4 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
   5 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
31437 => array(
  'title' => 'COPD',
  'nid' => 31437,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
31430 => array(
  'title' => 'Crohns Disease',
  'nid' => 31430,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
37218 => array(
  'title' => 'Cymbalta',
  'nid' => 37218,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
   2 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
   3 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
  4 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
44599 => array(
  'title' => 'Cystic Fibrosis',
  'nid' => 44599,
   'taxonomy' => array(
  0 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  1 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
   2 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   3 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
  4 => array(
      'title' => 'Diabetes',
      'nid' => 29177
    ),
   5 => array(
      'title' => 'Infertility',
      'nid' => 29190
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
31953 => array(
  'title' => 'Dads',
  'nid' => 31953,
   'taxonomy' => array(
  0 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  1 => array(
      'title' => 'Single Dads',
      'nid' => 44609
    ),
   2 => array(
      'title' => 'Single Parents',
      'nid' => 29348
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
44592 => array(
  'title' => 'Dementia',
  'nid' => 44592,
   'taxonomy' => array(
  0 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   3 => array(
      'title' => 'Alzheimers',
      'nid' => 31449
    ),
  4 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
29176 => array(
  'title' => 'Depression',
  'nid' => 29176,
   'taxonomy' => array(
  0 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  1 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   2 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
   3 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
  4 => array(
      'title' => 'Panic Attack',
      'nid' => 29890
    ),
   5 => array(
      'title' => 'Post Partum Depression',
      'nid' => 44605
    ),
  6 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
   7 => array(
      'title' => 'College',
      'nid' => 29175
    ),
   8 => array(
      'title' => 'Teen ',
      'nid' => 31954
    ),
  9 => array(
      'title' => 'Seasonal Affective Disorder',
      'nid' => 52261
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
29177 => array(
  'title' => 'Diabetes',
  'nid' => 29177,
   'taxonomy' => array(
  0 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
  1 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
   2 => array(
      'title' => 'Depression',
      'nid' => 29196
    ),
   3 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
  4 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   5 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  6 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),
   7 => array(
      'title' => 'Weight Loss',
      'nid' => 29208
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
47190 => array(
  'title' => 'Diverticulitis',
  'nid' => 47190,
   'taxonomy' => array(
  0 => array(
      'title' => 'Irritable Bowel Syndrome',
      'nid' => 35203
    ),
  1 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
   2 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
29178 => array(
  'title' => 'Divorce',
  'nid' => 29178,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
   2 => array(
      'title' => 'Relationships',
      'nid' => 29199
    ),
   3 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
  4 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   5 => array(
      'title' => 'Single Parents',
      'nid' => 29348
    ),
  6 => array(
      'title' => 'Single Moms',
      'nid' => 44610
    ),
   7 => array(
      'title' => 'Single Dads',
      'nid' => 44609
    ),
   8 => array(
      'title' => 'Infidelity',
      'nid' => 29191
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
 31452 => array(
  'title' => 'Dizziness',
  'nid' =>  31452,
   'taxonomy' => array(
  0 => array(
      'title' => 'Anemia',
      'nid' => 37212
    ),
  1 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
 44604 => array(
  'title' => 'Down Syndrome',
  'nid' =>  44604,
   'taxonomy' => array(
  0 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  1 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
  2 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   3 => array(
      'title' => 'Learning Disabilities',
      'nid' => 40265
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
29027 => array(
  'title' => 'Drug',
  'nid' =>  29027,
   'taxonomy' => array(
  0 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
  1 => array(
      'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  2 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   3 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
35231 => array(
  'title' => 'Dyslexia',
  'nid' =>  35231,
   'taxonomy' => array(
  0 => array(
      'title' => 'Learning Disabilities',
      'nid' => 40265
    ),
  1 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  2 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
   3 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
  4 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
   5 => array(
      'title' => 'College',
      'nid' => 29175
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
29179 => array(
  'title' => 'Eating Disorder',
  'nid' =>  29179,
   'taxonomy' => array(
  0 => array(
      'title' => 'Bulimia',
      'nid' => 29174
    ),
  1 => array(
      'title' => 'Body Dysmorphic Disorder',
      'nid' => 40267
    ),
  2 => array(
      'title' => 'Binge Eating',
      'nid' => 29170
    ),
   3 => array(
      'title' => 'Anorexia',
      'nid' => 29167
    ),
  4 => array(
      'title' => 'Healthy Eating',
      'nid' => 3522
    ),
   5 => array(
      'title' => 'EDNOS',
      'nid' => 38499
    ),
  6 => array(
      'title' => 'Exercise Addiction',
      'nid' => 40263
    ),
  7 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
8 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
9 => array(
      'title' => 'College',
      'nid' => 29175
    ),
10 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
11 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
43572 => array(
  'title' => 'Ecstasy',
  'nid' =>  43572,
   'taxonomy' => array(
  0 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
  1 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
  2 => array(
      'title' => 'College',
      'nid' => 29175
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
31444 => array(
  'title' => 'Eczema',
  'nid' =>  31444,
   'taxonomy' => array(
  0 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
38499 => array(
  'title' => 'EDNOS',
  'nid' =>  38499,
   'taxonomy' => array(
  0 => array(
      'title' => 'Eating Disorder',
      'nid' => 29179
    ),
  1 => array(
      'title' => 'Bulimia',
      'nid' => 29174
    ),
  2 => array(
      'title' => 'Body Dysmorphic Disorder',
      'nid' => 40267
    ),
   3 => array(
      'title' => 'Binge Eating',
      'nid' => 29170
    ),
  4 => array(
      'title' => 'Anorexia',
      'nid' => 29167
    ),
   5 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
6 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),
  7 => array(
      'title' => 'Exercise Addiction',
      'nid' => 40263
    ),
  8 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
9 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
10 => array(
      'title' => 'College',
      'nid' => 29175
    ),
11 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
35205 => array(
  'title' => 'Emotional Abuse',
  'nid' =>  35205,
   'taxonomy' => array(
  0 => array(
      'title' => 'Abuse',
      'nid' => 29162
    ),
  1 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  2 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
   3 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
  4 => array(
      'title' => 'Divorce',
      'nid' => 29178
    ),
   5 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
6 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
  7 => array(
      'title' => 'Depression',
      'nid' => 40263
    ),
  8 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
31428 => array(
  'title' => 'Endometriosis',
  'nid' =>  31428,
   'taxonomy' => array(
  0 => array(
      'title' => 'Infertility',
      'nid' => 29190
    ),
  1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
      'title' => 'Trying to Conceive',
      'nid' => 44595
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
29913 => array(
  'title' => 'Epilepsy',
  'nid' =>  29913,
   'taxonomy' => array(
  0 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  1 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
  2 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   3 => array(
      'title' => 'Klonopin',
      'nid' => 37219
    ),
  4 => array(
      'title' => 'Neurontin',
      'nid' => 37227
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
44603 => array(
  'title' => 'Erectile Dysfunction',
  'nid' =>  44603,
   'taxonomy' => array(
  0 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
  1 => array(
      'title' => 'Healthy Sex',
      'nid' => 29188
    ),
  2 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   3 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  4 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   5 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
40263 => array(
  'title' => 'Exercise Addiction',
  'nid' =>  40263,
   'taxonomy' => array(
  0 => array(
      'title' => 'EDNOS',
      'nid' => 38499
    ),
  1 => array(
      'title' => 'Eating Disorder',
      'nid' => 29179
    ),
  2 => array(
      'title' => 'Bulimia',
      'nid' => 29174
    ),
   3 => array(
      'title' => 'Body Dysmorphic Disorder',
      'nid' => 40267
    ),
  4 => array(
      'title' => 'Binge Eating',
      'nid' => 29170
    ),
   5 => array(
      'title' => 'Anorexia',
      'nid' => 29167
    ),
6 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
  7 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),
  8 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
9 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
10 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
11 => array(
      'title' => 'College',
      'nid' => 29175
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
29180 => array(
  'title' => 'Family',
  'nid' =>  29180,
   'taxonomy' => array(
  0 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  1 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
  2 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   3 => array(
      'title' => 'Single Parents',
      'nid' => 29348
    ),
 4 => array(
      'title' => 'Single Moms',
      'nid' => 44610
    ),
5 => array(
      'title' => 'Single Dads',
      'nid' => 44609
    ),
  6 => array(
      'title' => 'Siblings',
      'nid' => 57786
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
29181 => array(
  'title' => 'Fibromyalgia',
  'nid' =>  29181,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
      'title' => 'Lyrica',
      'nid' => 37223
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
29182 => array(
  'title' => 'Financial Problems',
  'nid' =>  29182,
   'taxonomy' => array(
  0 => array(
      'title' => 'Unemployment',
      'nid' => 31082
    ),
  1 => array(
      'title' => 'Gambling',
      'nid' => 29185
    ),
  2 => array(
      'title' => 'Career Changes',
      'nid' => 44600
    ),
   3 => array(
      'title' => 'Depressions',
      'nid' => 29176
    ),
 4 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
5 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
29183 => array(
  'title' => 'Food Allergy',
  'nid' =>  29183,
   'taxonomy' => array(
  0 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
  1 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
  2 => array(
      'title' => 'Celiac Disease',
      'nid' => 31443
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
29184 => array(
  'title' => 'Friends and Family of Addicts',
  'nid' =>  29184,
   'taxonomy' => array(
  0 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  1 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
  2 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   3 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
 4 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
5 => array(
      'title' => 'Alcohol',
      'nid' => 29165
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
102839 => array(
  'title' => 'Friends and Family of BPD',
  'nid' =>  102839,
   'taxonomy' => array(
  0 => array(
      'title' => 'BPD',
      'nid' => 29172
    ),
  1 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
29185 => array(
  'title' => 'Gambling',
  'nid' => 29185,
   'taxonomy' => array(
  0 => array(
      'title' => 'Financial Problems',
      'nid' => 29182
    ),
  1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
   3 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
29186 => array(
  'title' => 'Gay and Lesbian',
  'nid' => 29186,
   'taxonomy' => array(
  0 => array(
      'title' => 'Coming Out',
      'nid' => 47181
    ),
  1 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
  2 => array(
      'title' => 'College',
      'nid' => 29175
    ),
   3 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
 4 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
44623 => array(
  'title' => 'Graves Disease',
  'nid' => 44623,
   'taxonomy' => array(
  0 => array(
      'title' => 'Hyperthyroidism',
      'nid' => 44596
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29187 => array(
  'title' => 'Grief',
  'nid' => 29187,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
  2 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
37211 => array(
  'title' => 'Hair Loss',
  'nid' => 37211,
   'taxonomy' => array(
  0 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
35227 => array(
  'title' => 'Healthy Eating',
  'nid' => 35227,
   'taxonomy' => array(
  0 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29188 => array(
  'title' => 'Healthy Sex',
  'nid' => 29188,
   'taxonomy' => array(
  0 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44606 => array(
  'title' => 'Heart Attack',
  'nid' => 44606,
   'taxonomy' => array(
  0 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),
  1 => array(
      'title' => 'High Blood Pressure',
      'nid' => 35229
    ),
  2 => array(
      'title' => 'Heart Disease',
      'nid' => 29189
    ),
   3 => array(
      'title' => 'High Cholesterol',
      'nid' => 44601
    ),
 4 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
5 => array(
      'title' => 'Smoking',
      'nid' => 29205
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
29189 => array(
  'title' => 'Heart Disease',
  'nid' => 29189,
   'taxonomy' => array(
  0 => array(
      'title' => 'Heart Attack',
      'nid' => 44606
    ),
  1 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),
  2 => array(
      'title' => 'High Blood Pressure',
      'nid' => 35229
    ),
3 => array(
      'title' => 'Smoking',
      'nid' => 29205
    ),
   4 => array(
      'title' => 'High Cholesterol',
      'nid' => 44601
    ),
 5 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
31441 => array(
  'title' => 'Heartburn',
  'nid' => 31441,
   'taxonomy' => array(
  0 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  2 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
3 => array(
      'title' => 'Pregnancy',
      'nid' => 29903
    ),
   4 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
35226 => array(
  'title' => 'Hepatitis C',
  'nid' => 35226,
   'taxonomy' => array(
  0 => array(
      'title' => 'Cirrhosis',
      'nid' => 35232
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
35209 => array(
  'title' => 'Heroin',
  'nid' => 35209,
   'taxonomy' => array(
  0 => array(
      'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  1 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
  2 => array(
      'title' => 'Methadone',
      'nid' => 37241
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
29930 => array(
  'title' => 'Herpes',
  'nid' => 29930,
   'taxonomy' => array(
  0 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
3 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
35229 => array(
  'title' => 'High Blood Pressure',
  'nid' => 35229,
   'taxonomy' => array(
  0 => array(
      'title' => 'Heart Attack',
      'nid' => 44606
    ),
  1 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),
  2 => array(
      'title' => 'Healty Eating',
      'nid' => 35227
    ),
3 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   4 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
 5 => array(
      'title' => 'Panic Attack',
      'nid' => 29890
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
44601 => array(
  'title' => 'High Cholesterol',
  'nid' => 44601,
   'taxonomy' => array(
  0 => array(
      'title' => 'Heart Attack',
      'nid' => 44606
    ),
  1 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),
  2 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
3 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29920 => array(
  'title' => 'HIV',
  'nid' => 29920,
   'taxonomy' => array(
  0 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
  1 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
  2 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
3 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   
   )
 ),
 // End of Item



// Start of item
// Id of the group
44612 => array(
  'title' => 'Hives',
  'nid' => 44612,
   'taxonomy' => array(
  0 => array(
      'title' => 'Food Allergy',
      'nid' => 29183
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44590 => array(
  'title' => 'Hoarding',
  'nid' => 44590,
   'taxonomy' => array(
  0 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  1 => array(
      'title' => 'OCD',
      'nid' => 29194
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
57785 => array(
  'title' => 'HOCD',
  'nid' => 57785,
   'taxonomy' => array(
  0 => array(
      'title' => 'OCD',
      'nid' => 29194
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29209 => array(
  'title' => 'Hodgkins Lymphoma',
  'nid' => 29209,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  2 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
3 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
31442 => array(
  'title' => 'HPV',
  'nid' => 31442,
   'taxonomy' => array(
  0 => array(
      'title' => 'Cervical Cancer',
      'nid' => 35216
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
47182 => array(
  'title' => 'Huntingtons Disease',
  'nid' => 47182,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44596 => array(
  'title' => 'Hyperthyroidism',
  'nid' => 44596,
   'taxonomy' => array(
  0 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44621 => array(
  'title' => 'Hypothyroidism',
  'nid' => 44621,
   'taxonomy' => array(
  0 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),
  1 => array(
      'title' => 'Heart Disease',
      'nid' => 29189
    ),
  2 => array(
      'title' => 'Infertility',
      'nid' => 29190
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
44621 => array(
  'title' => 'Hysterectomy',
  'nid' => 44621,
   'taxonomy' => array(
  0 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
  1 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
  2 => array(
      'title' => 'Menopause',
      'nid' => 29915
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
44597 => array(
  'title' => 'Incest Survivors',
  'nid' => 44597,
   'taxonomy' => array(
  0 => array(
      'title' => 'Abuse',
      'nid' => 29162
    ),
  1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
3 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   4 => array(
      'title' => 'Sexual Abuse',
      'nid' => 44617
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
29190 => array(
  'title' => 'Infertility',
  'nid' => 29190,
   'taxonomy' => array(
  0 => array(
      'title' => 'PCOS',
      'nid' => 35206
    ),
  1 => array(
      'title' => 'Trying to conceive',
      'nid' => 44595
    ),
  2 => array(
      'title' => 'Endometriosis',
      'nid' => 31428
    ),
3 => array(
      'title' => 'Miscarriage',
      'nid' => 29893
    ),
   4 => array(
      'title' => 'Hypothyroidism',
      'nid' => 44621
    ),
 5 => array(
      'title' => 'Premature Ovarian Failure',
      'nid' => 37214
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
29191 => array(
  'title' => 'Infidelity',
  'nid' => 29191,
   'taxonomy' => array(
  0 => array(
      'title' => 'Divorce',
      'nid' => 29178
    ),
  1 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
  2 => array(
      'title' => 'Jealousy',
      'nid' => 35234
    ),
3 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   4 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
 5 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29192 => array(
  'title' => 'Insomnia',
  'nid' => 29192,
   'taxonomy' => array(
  0 => array(
      'title' => 'Ambien',
      'nid' => 37216
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  2 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
35211 => array(
  'title' => 'Internet Addiction',
  'nid' => 35211,
   'taxonomy' => array(
  0 => array(
      'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  1 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
  2 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
3 => array(
      'title' => 'College',
      'nid' => 29175
    ),
   4 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
35203 => array(
  'title' => 'Irritable Bowel Syndrome',
  'nid' => 35203,
   'taxonomy' => array(
  0 => array(
      'title' => 'Diverticulitis',
      'nid' => 47190
    ),
  1 => array(
      'title' => 'Crohns Disease',
      'nid' => 31430
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
35234 => array(
  'title' => 'Jealousy',
  'nid' => 35234,
   'taxonomy' => array(
  0 => array(
      'title' => 'Divorce',
      'nid' => 29178
    ),
  1 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
  2 => array(
      'title' => 'Infidelity',
      'nid' => 29191
    ),
3 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   4 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
 5 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  6 => array(
      'title' => 'Anger Management',
      'nid' => 29166
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
35218 => array(
  'title' => 'Kidney Cancer',
  'nid' => 35218,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  2 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
3 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44615 => array(
  'title' => 'Kleptomania',
  'nid' => 44615,
   'taxonomy' => array(
  0 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  1 => array(
      'title' => 'Eating Disorder',
      'nid' => 29179
    ),
  2 => array(
      'title' => 'Alcohol',
      'nid' => 29165
    ),
3 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
   4 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
37219 => array(
  'title' => 'Klonopin',
  'nid' => 37219,
   'taxonomy' => array(
  0 => array(
      'title' => 'Epilepsy',
      'nid' => 29913
    ),
  1 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
  2 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
3 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
   4 => array(
      'title' => 'Panic Attack',
      'nid' => 29890
    ),
 5 => array(
      'title' => 'Social Anxiety',
      'nid' => 29168
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
40265 => array(
  'title' => 'Learning Disability',
  'nid' => 40265,
   'taxonomy' => array(
  0 => array(
      'title' => 'Dyslexia',
      'nid' => 35231
    ),
  1 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  2 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
3 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   4 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
35219 => array(
  'title' => 'Liver Cancer',
  'nid' => 35219,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  2 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
3 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
29193 => array(
  'title' => 'Loneliness',
  'nid' => 29193,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  2 => array(
      'title' => 'Social Anxiety',
      'nid' => 29168
    ),
3 => array(
      'title' => 'Grief',
      'nid' => 29187
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
29924 => array(
  'title' => 'Lung Cancer',
  'nid' => 29924,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  2 => array(
     'title' => 'Medicare',
      'nid' => 47183
    ),
3 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
44620 => array(
  'title' => 'Lupus',
  'nid' => 44620,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chronic Fatigue Syndrome',
      'nid' => 29911
    ),
  1 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  2 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
44594 => array(
  'title' => 'Lyme Disease',
  'nid' => 44594,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
59290 => array(
  'title' => 'Lymphedema',
  'nid' => 59290,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
37223 => array(
  'title' => 'Lyrica',
  'nid' => 37223,
   'taxonomy' => array(
  0 => array(
      'title' => 'Fibromyalgia',
      'nid' => 29181
    ),
  1 => array(
       'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  2 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
31435 => array(
  'title' => 'Marijuana',
  'nid' => 31435,
   'taxonomy' => array(
  0 => array(
      'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  1 => array(
       'title' => 'Teen',
      'nid' => 31954
    ),
  2 => array(
     'title' => 'College',
      'nid' => 29175
    ),
3 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   4 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
 5 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
47184 => array(
  'title' => 'Medicaid',
  'nid' => 47184,
   'taxonomy' => array(
  0 => array(
      'title' => 'Financial Problems',
      'nid' => 29182
    ),
  1 => array(
       'title' => 'Caregiver',
      'nid' => 44622
    ),
  2 => array(
     'title' => 'Medicare',
      'nid' => 47183
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
47183 => array(
  'title' => 'Medicare',
  'nid' => 47183,
   'taxonomy' => array(
  0 => array(
      'title' => 'Financial Problems',
      'nid' => 29182
    ),
  1 => array(
       'title' => 'Caregiver',
      'nid' => 44622
    ),
  2 => array(
     'title' => 'Medicaid',
      'nid' => 47184
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
29915 => array(
  'title' => 'Menopause',
  'nid' => 29915,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
       'title' => 'Hysterectomy',
      'nid' => 35230
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
37224 => array(
  'title' => 'Metformin',
  'nid' => 37224,
   'taxonomy' => array(
  0 => array(
      'title' => 'Diabetes',
      'nid' => 29177
    ),
  1 => array(
       'title' => 'PCOS',
      'nid' => 35206
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
37224 => array(
  'title' => 'Meth',
  'nid' => 37224,
   'taxonomy' => array(
  0 => array(
      'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  1 => array(
       'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
     'title' => 'Anxiety',
      'nid' => 29168
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
37241 => array(
  'title' => 'Methadone',
  'nid' => 37241,
   'taxonomy' => array(
  0 => array(
      'title' => 'Heroin',
      'nid' => 35209
    ),
  1 => array(
      'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  2 => array(
     'title' => 'Morphine',
      'nid' => 37225
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
31425 => array(
  'title' => 'Migraine',
  'nid' => 31425,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  1 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
31436 => array(
  'title' => 'Military Family',
  'nid' => 31436,
   'taxonomy' => array(
  0 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
  1 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
  2 => array(
     'title' => 'Dads',
      'nid' => 31953
    ),
3 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
   4 => array(
      'title' => 'PTSD',
      'nid' => 29198
    ),
 5 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  6 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
 
   )
 ),
 // End of Item
// Start of item
// Id of the group
29893 => array(
  'title' => 'Miscarriage',
  'nid' => 29893,
   'taxonomy' => array(
  0 => array(
      'title' => 'Grief',
      'nid' => 29187
    ),
  1 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
  2 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
31952 => array(
  'title' => 'Moms',
  'nid' => 31952,
   'taxonomy' => array(
  0 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  1 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
  2 => array(
     'title' => 'Stress',
      'nid' => 29206
    ),
3 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   4 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
 5 => array(
       'title' => 'Loneliness',
      'nid' => 29193
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
37225 => array(
  'title' => 'Morphine',
  'nid' => 37225,
   'taxonomy' => array(
  0 => array(
      'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  1 => array(
      'title' => 'Methadone',
      'nid' => 37241
    ),
  2 => array(
     'title' => 'Drug',
      'nid' => 29027
    ),
3 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
29887 => array(
  'title' => 'Multiple Sclerosis',
  'nid' => 29887,
   'taxonomy' => array(
  0 => array(
      'title' => 'Dizziness',
      'nid' => 31452
    ),
  1 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
37226 => array(
  'title' => 'Naproxen',
  'nid' => 37226,
   'taxonomy' => array(
  0 => array(
      'title' => 'Arthtritis',
      'nid' => 29918
    ),
  1 => array(
      'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  2 => array(
     'title' => 'Drug',
      'nid' => 29027
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
52265 => array(
  'title' => 'Narcissist',
  'nid' => 52265,
   'taxonomy' => array(
  0 => array(
      'title' => 'Emotional Abuse',
      'nid' => 35205
    ),
  1 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  2 => array(
     'title' => 'Relationship',
      'nid' => 29199
    ),
3 => array(
      'title' => 'Abuse',
      'nid' => 29162
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
44593 => array(
  'title' => 'Narcolepsy',
  'nid' => 44593,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
37227 => array(
  'title' => 'Neurontin',
  'nid' => 37227,
   'taxonomy' => array(
  0 => array(
      'title' => 'Epilepsy',
      'nid' => 29913
    ),
  1 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  2 => array(
     'title' => 'Moms',
      'nid' => 31952
    ),
3 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
29210 => array(
  'title' => 'Non Hodgkins Lymphoma',
  'nid' => 29210,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  2 => array(
     'title' => 'Medicare',
      'nid' => 47183
    ),
3 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44613 => array(
  'title' => 'Nutrition',
  'nid' => 44613,
   'taxonomy' => array(
  0 => array(
      'title' => 'Vegan',
      'nid' => 47185
    ),
  1 => array(
      'title' => 'Vegetarian',
      'nid' => 47186
    ),
  2 => array(
     'title' => 'Celiac Disease',
      'nid' => 31443
    ),
3 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
   4 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),
 5 => array(
       'title' => 'Diabetes',
      'nid' => 29177
    ),
  6 => array(
      'title' => 'Eating Disorder',
      'nid' => 29179
    ),
  7 => array(
      'title' => 'Anorexia',
      'nid' => 29167
    ),
  8 => array(
      'title' => 'Bulimia',
      'nid' => 29174
    ),

   )
 ),
 // End of Item
// Start of item
// Id of the group
44618 => array(
  'title' => 'Obesity',
  'nid' => 44618,
   'taxonomy' => array(
  0 => array(
      'title' => 'Diabetes',
      'nid' => 29177
    ),
  1 => array(
      'title' => 'Heart Attack',
      'nid' => 44606
    ),
  2 => array(
     'title' => 'Heart Disease',
      'nid' => 29189
    ),
3 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
   4 => array(
      'title' => 'Nutrition',
      'nid' => 44613
    ),

   )
 ),
 // End of Item



// Start of item
// Id of the group
29194 => array(
  'title' => 'OCD',
  'nid' => 29194,
   'taxonomy' => array(
  0 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  1 => array(
      'title' => 'Social Anxiety',
      'nid' => 29168
    ),
  2 => array(
     'title' => 'Stress',
      'nid' => 29206
    ),
3 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   4 => array(
      'title' => 'Panic Attack',
      'nid' => 29890
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
31956 => array(
  'title' => 'Online Dating',
  'nid' => 31956,
   'taxonomy' => array(
  0 => array(
      'title' => 'Singles',
      'nid' => 29204
    ),
  1 => array(
      'title' => 'Single Moms',
      'nid' => 44610
    ),
  2 => array(
     'title' => 'Single Dads',
      'nid' => 44609
    ),
3 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
   4 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
35233 => array(
  'title' => 'Osteoporosis',
  'nid' => 35233,
   'taxonomy' => array(
  0 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
  1 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
  2 => array(
     'title' => 'Chronic Pain',
      'nid' => 29901
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
35221 => array(
  'title' => 'Ovarian Cancer',
  'nid' => 35221,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  2 => array(
     'title' => 'Medicare',
      'nid' => 47183
    ),
3 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
37228 => array(
  'title' => 'Oxycodone',
  'nid' => 37228,
   'taxonomy' => array(
  0 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
  1 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),
  2 => array(
     'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),

   )
 ),
 // End of Item
// Start of item
// Id of the group
35222 => array(
  'title' => 'Pancreatic Cancer',
  'nid' => 35222,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  2 => array(
     'title' => 'Medicare',
      'nid' => 47183
    ),
3 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
   4 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),

   )
 ),
 // End of Item


// Start of item
// Id of the group
29890 => array(
  'title' => 'Panic Attack',
  'nid' => 29890,
   'taxonomy' => array(
  0 => array(
      'title' => 'OCD',
      'nid' => 29194
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  2 => array(
     'title' => 'Social Anxiety',
      'nid' => 29168
    ),
3 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
   4 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
 5 => array(
       'title' => 'Xanax',
      'nid' => 37233
    ),
  6 => array(
      'title' => 'Klonopin',
      'nid' => 37219
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44607 => array(
  'title' => 'Paranoia',
  'nid' => 44607,
   'taxonomy' => array(
  0 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  2 => array(
     'title' => 'Panic Attack',
      'nid' => 29890
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
29195 => array(
  'title' => 'Parents',
  'nid' => 29195,
   'taxonomy' => array(
  0 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
  1 => array(
      'title' => 'Dads',
      'nid' => 31953
    ),
  2 => array(
     'title' => 'Family',
      'nid' => 29180
    ),
3 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
31439 => array(
  'title' => 'Parkinsons',
  'nid' => 31439,
   'taxonomy' => array(
  0 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
  1 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
  2 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
37238 => array(
  'title' => 'Paxil',
  'nid' => 37238,
   'taxonomy' => array(
  0 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  2 => array(
      'title' => 'OCD',
      'nid' => 29194
    ),
3 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
   4 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
35206 => array(
  'title' => 'PCOS',
  'nid' => 35206,
   'taxonomy' => array(
  0 => array(
     'title' => 'Miscarriage',
      'nid' => 29893
    ),
  1 => array(
      'title' => 'Endometriosis',
      'nid' => 31428
    ),
  2 => array(
      'title' => 'Trying to Conceive',
      'nid' => 44595
    ),
3 => array(
      'title' => 'Infertility',
      'nid' => 29190
    ),
   4 => array(
      'title' => 'Weight Loss',
      'nid' => 29208
    ),
 5 => array(
       'title' => 'Metformin',
      'nid' => 37224
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
37243 => array(
  'title' => 'Percocet',
  'nid' => 37243,
   'taxonomy' => array(
  0 => array(
     'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  1 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
  2 => array(
      'title' => 'Prescription Drug',
      'nid' => 29196
    ),

   )
 ),
 // End of Item



// Start of item
// Id of the group
31433 => array(
  'title' => 'Personality Disorder',
  'nid' => 31433,
   'taxonomy' => array(
  0 => array(
     'title' => 'Anxiety',
      'nid' => 29168
    ),
  1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
 37213 => array(
  'title' => 'Pet Loss',
  'nid' =>  37213,
   'taxonomy' => array(
  0 => array(
     'title' => 'Grief',
      'nid' => 29187
    ),
  1 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
 29922 => array(
  'title' => 'Phobia',
  'nid' =>  29922,
   'taxonomy' => array(
  0 => array(
     'title' => 'Stress',
      'nid' => 29206
    ),
  1 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  2 => array(
      'title' => 'Agoraphobia',
      'nid' => 35204
    ),
3 => array(
      'title' => 'Social Anxiety',
      'nid' => 29168
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44616 => array(
  'title' => 'Plastic Surgery',
  'nid' =>  44616,
   'taxonomy' => array(
  0 => array(
     'title' => 'Surgery',
      'nid' => 31632
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
31450 => array(
  'title' => 'PMS',
  'nid' =>  31450,
   'taxonomy' => array(
  0 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29176 => array(
  'title' => 'Post Partum Depression',
  'nid' =>  29176,
   'taxonomy' => array(
  0 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
      'title' => 'Moms',
      'nid' => 31952
    ),
  2 => array(
      'title' => 'Pregnancy',
      'nid' => 29903
    ),
3 => array(
      'title' => 'Breastfeeding',
      'nid' => 44598
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
29176 => array(
  'title' => 'Pregnancy',
  'nid' =>  29176,
   'taxonomy' => array(
  0 => array(
     'title' => 'Moms',
      'nid' => 31952
    ),
  1 => array(
      'title' => 'Single Moms',
      'nid' => 44610
    ),
  2 => array(
      'title' => 'Relationship',
      'nid' => 29199
    ),
3 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
   4 => array(
      'title' => 'Trying to Conceive',
      'nid' => 44595
    ),
 5 => array(
       'title' => 'Breastfeeding',
      'nid' => 44598
    ),
  6 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
37214 => array(
  'title' => 'Premature Ovarian Failure',
  'nid' =>  37214,
   'taxonomy' => array(
  0 => array(
     'title' => 'Infertility',
      'nid' => 29190
    ),
  1 => array(
      'title' => 'Miscarriage',
      'nid' => 29893
    ),
  2 => array(
      'title' => 'Endometriosis',
      'nid' => 31428
    ),
3 => array(
      'title' => 'Trying to Conceive',
      'nid' => 44595
    ),
   4 => array(
      'title' => 'Trying to Conceive',
      'nid' => 44595
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
29196 => array(
  'title' => 'Prescription Drug',
  'nid' => 29196,
   'taxonomy' => array(
  0 => array(
     'title' => 'Drug',
      'nid' => 29027
    ),
  1 => array(
      'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29197 => array(
  'title' => 'Prostate Cancer',
  'nid' => 29197,
   'taxonomy' => array(
  0 => array(
     'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
      'title' => 'Caregivers',
      'nid' => 29184
    ),
  2 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
3 => array(
      'title' => 'Medicaid',
      'nid' => 47184
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
31440 => array(
  'title' => 'Psoriasis',
  'nid' => 31440,
   'taxonomy' => array(
  0 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  2 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
29198 => array(
  'title' => 'PTSD',
  'nid' => 29198,
   'taxonomy' => array(
  0 => array(
     'title' => 'Stress',
      'nid' => 29206
    ),
  1 => array(
      'title' => 'Insomnia',
      'nid' => 29192
    ),
  2 => array(
      'title' => 'Alcohol',
      'nid' => 29165
    ),
3 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
   4 => array(
      'title' => 'Anger Management',
      'nid' => 29166
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
29907 => array(
  'title' => 'Rape',
  'nid' => 29907,
   'taxonomy' => array(
  0 => array(
     'title' => 'PTSD',
      'nid' => 29198
    ),
  1 => array(
    'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
      'title' => 'Sexual Abuse',
      'nid' => 44617
    ),
3 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
   4 => array(
      'title' => 'Abuse',
      'nid' => 29162
    ),
 5 => array(
     'title' => 'Relationship',
      'nid' => 29199
    ),
  6 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29199 => array(
  'title' => 'Relationship',
  'nid' => 29199,
   'taxonomy' => array(
  0 => array(
     'title' => 'Family',
      'nid' => 29180
    ),
  1 => array(
    'title' => 'Healthy Sex',
      'nid' => 29188
    ),
  2 => array(
      'title' => 'Online Dating',
      'nid' => 31956
    ),
3 => array(
      'title' => 'Singles',
      'nid' =>  29204
    ),
   4 => array(
      'title' => 'Divorce',
      'nid' => 29178
    ),
 5 => array(
     'title' => 'Jealousy',
      'nid' => 35234
    ),
  6 => array(
      'title' => 'Infidelity',
      'nid' => 29191
    ),
  7 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
35207 => array(
  'title' => 'Rosacea',
  'nid' => 35207,
   'taxonomy' => array(
  0 => array(
     'title' => 'Self Esteem',
      'nid' => 29932
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29200 => array(
  'title' => 'Schizophrenia',
  'nid' => 29200,
   'taxonomy' => array(
  0 => array(
     'title' => 'Anxiety',
      'nid' => 29168
    ),
  1 => array(
    'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
      'title' => 'Paranoia',
      'nid' => 44607
    ),
3 => array(
      'title' => 'Seroquel',
      'nid' =>  37229
    ),
 
   )
 ),
 // End of Item
// Start of item
// Id of the group
47193 => array(
  'title' => 'Sciatica',
  'nid' => 47193,
   'taxonomy' => array(
  0 => array(
     'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  1 => array(
    'title' => 'Back Pain',
      'nid' => 31426
    ),
 
   )
 ),
 // End of Item


// Start of item
// Id of the group
35228 => array(
  'title' => 'Scoliosis',
  'nid' => 35228,
   'taxonomy' => array(
  0 => array(
     'title' => 'Teen',
      'nid' => 31954
    ),
  1 => array(
    'title' => 'Back Pain',
      'nid' => 31426
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
52261 => array(
  'title' => 'Seasonal Affective Disorder',
  'nid' => 52261,
   'taxonomy' => array(
  0 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
    'title' => 'Anxiety',
      'nid' => 29168
    ),
  2 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
29932 => array(
  'title' => 'Self Esteem',
  'nid' => 29932,
   'taxonomy' => array(
  0 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
    'title' => 'Anxiety',
      'nid' => 29168
    ),
  2 => array(
      'title' => 'Social Anxiety',
      'nid' => 29168
    ),
3 => array(
     'title' => 'Loneliness',
      'nid' => 29193
    ),
   4 => array(
      'title' => 'Teen',
      'nid' => 31954
    ),
 5 => array(
     'title' => 'Eating Disorder',
      'nid' => 29179
    ),
  6 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),
  
   )
 ),
 // End of Item


// Start of item
// Id of the group
29201 => array(
  'title' => 'Self Harm',
  'nid' => 29201,
   'taxonomy' => array(
  0 => array(
     'title' => 'Self Esteem',
      'nid' => 29932
    ),
  1 => array(
    'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
       'title' => 'Anxiety',
      'nid' => 29168
    ),
3 => array(
    'title' => 'Social Anxiety',
      'nid' => 29168
    ),
   4 => array(
      'title' => 'Loneliness',
      'nid' => 29193
    ),
 5 => array(
     'title' => 'Teen',
      'nid' => 31954
    ),
  6 => array(
     'title' => 'Eating Disorder',
      'nid' => 29179
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
37229 => array(
  'title' => 'Seroquel',
  'nid' => 37229,
   'taxonomy' => array(
  0 => array(
     'title' => 'Bipolar',
      'nid' => 29171
    ),
  1 => array(
    'title' => 'Schizophrenia',
      'nid' => 29200
    ),
 
   )
 ),
 // End of Item

// Start of item
// Id of the group
29202 => array(
  'title' => 'Sex Addiction',
  'nid' => 29202,
   'taxonomy' => array(
  0 => array(
     'title' => 'Healthy Sex',
      'nid' => 29188
    ),
  1 => array(
    'title' => 'Relationship',
      'nid' => 29199
    ),
  2 => array(
       'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),

   )
 ),
 // End of Item

// Start of item
// Id of the group
44617 => array(
  'title' => 'Sexual Abuse',
  'nid' => 44617,
   'taxonomy' => array(
  0 => array(
     'title' => 'Abuse',
      'nid' => 29162
    ),
  1 => array(
    'title' => 'Rape',
      'nid' => 29907
    ),
  2 => array(
       'title' => 'Depression',
      'nid' => 29176
    ),
3 => array(
    'title' => 'Self Esteem',
      'nid' => 29932
    ),
   4 => array(
      'title' => 'Self Harm',
      'nid' => 29201
    ),
 5 => array(
     'title' => 'PTSD',
      'nid' => 29198
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
40268 => array(
  'title' => 'Sexual Harassment',
  'nid' => 40268,
   'taxonomy' => array(
  0 => array(
     'title' => 'Self Esteem',
      'nid' => 29932
    ),
  1 => array(
    'title' => 'Depression',
      'nid' => 29176
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29203 => array(
  'title' => 'Shopping Addiction',
  'nid' => 29203,
   'taxonomy' => array(
  0 => array(
     'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  1 => array(
    'title' => 'Financial Problems',
      'nid' => 29182
    ),
  2 => array(
    'title' => 'Depression',
      'nid' => 29176
    ),
  3 => array(
       'title' => 'Anxiety',
      'nid' => 29168
    ),
4 => array(
    'title' => 'Stress',
      'nid' => 29206
    ),
   5 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
40264 => array(
  'title' => 'Shyness',
  'nid' => 40264,
   'taxonomy' => array(
  0 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  1 => array(
    'title' => 'Social Anxiety',
      'nid' => 29168
    ),
  2 => array(
     'title' => 'Self Esteem',
      'nid' => 29932
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
57786 => array(
  'title' => 'Siblings',
  'nid' => 57786,
   'taxonomy' => array(
  0 => array(
      'title' => 'Family',
      'nid' => 29180
    ),
  1 => array(
    'title' => 'Codependency',
      'nid' => 29905
    ),
  2 => array(
   'title' => 'Stress',
      'nid' => 29206
    ),
  3 => array(
       'title' => 'Anxiety',
      'nid' => 29168
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44609 => array(
  'title' => 'Single Dads',
  'nid' => 44609,
   'taxonomy' => array(
  0 => array(
      'title' => 'Divorce',
      'nid' => 29178
    ),
  1 => array(
    'title' => 'Parents',
      'nid' => 29195
    ),
  2 => array(
   'title' => 'Family',
      'nid' => 29180
    ),
  3 => array(
       'title' => 'Online Dating',
      'nid' => 31956
    ),
4 => array(
    'title' => 'Single Parents',
      'nid' => 29348
    ),
   5 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44610 => array(
  'title' => 'Single Moms',
  'nid' => 44610,
   'taxonomy' => array(
  0 => array(
      'title' => 'Divorce',
      'nid' => 29178
    ),
  1 => array(
    'title' => 'Parents',
      'nid' => 29195
    ),
  2 => array(
   'title' => 'Family',
      'nid' => 29180
    ),
  3 => array(
       'title' => 'Online Dating',
      'nid' => 31956
    ),
4 => array(
    'title' => 'Single Parents',
      'nid' => 29348
    ),
   5 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29348 => array(
  'title' => 'Single Parents',
  'nid' => 29348,
   'taxonomy' => array(
  0 => array(
      'title' => 'Divorce',
      'nid' => 29178
    ),
  1 => array(
    'title' => 'Parents',
      'nid' => 29195
    ),
  2 => array(
   'title' => 'Family',
      'nid' => 29180
    ),
  3 => array(
       'title' => 'Online Dating',
      'nid' => 31956
    ),
4 => array(
    'title' => 'Single Moms',
      'nid' => 44610
    ),
   5 => array(
      'title' => 'Single Dads',
      'nid' => 44609
    ),
 6 => array(
     'title' => 'Stress',
      'nid' => 29206
    ),
    
   )
 ),
 // End of Item

// Start of item
// Id of the group
29204 => array(
  'title' => 'Singles',
  'nid' => 29204,
   'taxonomy' => array(
  0 => array(
      'title' => 'Single Parents',
      'nid' => 29348
    ),
  1 => array(
    'title' => 'Loneliness',
      'nid' => 29193
    ),
  2 => array(
   'title' => 'Family',
      'nid' => 29180
    ),
  3 => array(
       'title' => 'Online Dating',
      'nid' => 31956
    ),
4 => array(
    'title' => 'Single Moms',
      'nid' => 44610
    ),
   5 => array(
      'title' => 'Single Dads',
      'nid' => 44609
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29928 => array(
  'title' => 'Skin Cancer',
  'nid' => 29928,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
    'title' => 'Caregivers',
      'nid' => 44622
    ),
  2 => array(
   'title' => 'Medicare',
      'nid' => 47183
    ),
  3 => array(
       'title' => 'Medicaid',
      'nid' => 47184
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
40266 => array(
  'title' => 'Skin Picking',
  'nid' => 40266,
   'taxonomy' => array(
  0 => array(
      'title' => 'OCD',
      'nid' => 29194
    ),
  1 => array(
    'title' => 'Body Dysmorphic Disorder',
      'nid' => 40267
    ),
    
   )
 ),
 // End of Item

// Start of item
// Id of the group
47189 => array(
  'title' => 'Sleep Apnea',
  'nid' => 47189,
   'taxonomy' => array(
  0 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),
  1 => array(
    'title' => 'Smoking',
      'nid' => 29205
    ),
    
   )
 ),
 // End of Item

// Start of item
// Id of the group
52266 => array(
  'title' => 'Sleep Walking',
  'nid' => 52266,
   'taxonomy' => array(
  0 => array(
      'title' => 'Stress',
      'nid' => 29206
    ),
  1 => array(
    'title' => 'Anxiety',
      'nid' => 29168
    ),
  2 => array(
   'title' => 'Ambien',
      'nid' => 37216
    ),
  3 => array(
       'title' => 'Migraine',
      'nid' => 31425
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29205 => array(
  'title' => 'Smoking',
  'nid' => 29205,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chantix',
      'nid' => 37240
    ),
  1 => array(
    'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  2 => array(
   'title' => 'Stress',
      'nid' => 29206
    ),
  3 => array(
     'title' => 'Anxiety',
      'nid' => 29168
    ),
4 => array(
    'title' => 'Asthma',
      'nid' => 29909
    ),
   5 => array(
      'title' => 'COPD',
      'nid' => 31437
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
29168 => array(
  'title' => 'Social Anxiety',
  'nid' => 29168,
   'taxonomy' => array(
  0 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  1 => array(
     'title' => 'Stress',
      'nid' => 29206
    ),
  2 => array(
   'title' => 'Loneliness',
      'nid' => 29193
    ),
  3 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
52263 => array(
  'title' => 'Social Security',
  'nid' => 52263,
   'taxonomy' => array(
  0 => array(
      'title' => 'Medicare',
      'nid' => 47183
    ),
  1 => array(
     'title' => 'Medicaid',
      'nid' => 47184
    ),
  2 => array(
   'title' => 'Financial Problems',
      'nid' => 29182
    ),
    
   )
 ),
 // End of Item

// Start of item
// Id of the group
47194 => array(
  'title' => 'Spina Bifida',
  'nid' => 47194,
   'taxonomy' => array(
  0 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  1 => array(
     'title' => 'Family',
      'nid' => 29180
    ),
  2 => array(
   'title' => 'Moms',
      'nid' => 31952
    ),
  3 => array(
     'title' => 'Dads',
      'nid' => 31953
    ),
4 => array(
    'title' => 'Caregivers',
      'nid' => 44622
    ),
     
   )
 ),
 // End of Item

// Start of item
// Id of the group
29206 => array(
  'title' => 'Stress',
  'nid' => 29206,
   'taxonomy' => array(
  0 => array(
      'title' => 'Heart Disease',
      'nid' => 29189
    ),
  1 => array(
     'title' => 'Heart Attack',
      'nid' => 44606
    ),
  2 => array(
   'title' => 'Depression',
      'nid' => 29176
    ),
  3 => array(
     'title' => 'Loneliness',
      'nid' => 29193
    ),
4 => array(
    'title' => 'OCD',
      'nid' => 29194
    ),
     
   )
 ),
 // End of Item

// Start of item
// Id of the group
31451 => array(
  'title' => 'Stroke',
  'nid' => 31451,
   'taxonomy' => array(
  0 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  1 => array(
     'title' => 'Medicare',
      'nid' => 47183
    ),
  2 => array(
   'title' => 'Medicaid',
      'nid' => 47184
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44614 => array(
  'title' => 'Stuttering',
  'nid' => 44614,
   'taxonomy' => array(
  0 => array(
      'title' => 'Parents',
      'nid' => 29195
    ),
  1 => array(
     'title' => 'Moms',
      'nid' => 31952
    ),
  2 => array(
   'title' => 'Dads',
      'nid' => 31953
    ),
  3 => array(
   'title' => 'Stress',
      'nid' => 29206
    ),
4 => array(
    'title' => 'Anxiety',
      'nid' => 29168
    ),
   5 => array(
      'title' => 'Self Esteem',
      'nid' => 29932
    ),
 6 => array(
     'title' => 'Social Anxiety',
      'nid' => 29168
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
37245 => array(
  'title' => 'Suboxone',
  'nid' => 37245,
   'taxonomy' => array(
  0 => array(
      'title' => 'Drug',
      'nid' => 29027
    ),
  1 => array(
     'title' => 'Prescription Drug',
      'nid' => 29196
    ),
  2 => array(
   'title' => 'Friends and Family of Addicts',
      'nid' => 29184
    ),
  3 => array(
   'title' => 'Heroin',
      'nid' => 35209
    ),
4 => array(
    'title' => 'Morphine',
      'nid' => 37225
    ),
   5 => array(
      'title' => 'Methadone',
      'nid' => 37241
    ),
 6 => array(
     'title' => 'Oxycodone',
      'nid' => 37228
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
44591 => array(
  'title' => 'Sugar Addiction',
  'nid' => 44591,
   'taxonomy' => array(
  0 => array(
      'title' => 'Healthy Eating',
      'nid' => 35227
    ),
  1 => array(
     'title' => 'Nutrition',
      'nid' => 44613
    ),
  2 => array(
   'title' => 'Depression',
      'nid' => 29176
    ),
  3 => array(
   'title' => 'Binge Eating',
      'nid' => 29170
    ),
4 => array(
    'title' => 'Diabetes',
      'nid' => 29177
    ),
   5 => array(
      'title' => 'Obesity',
      'nid' => 44618
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29207 => array(
  'title' => 'Suicide',
  'nid' => 29207,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
     'title' => 'Loneliness',
      'nid' => 29193
    ),
  2 => array(
   'title' => 'Anxiety',
      'nid' => 29168
    ),
  3 => array(
   'title' => 'Stress',
      'nid' => 29206
    ),
4 => array(
    'title' => 'Family',
      'nid' => 29180
    ),
   5 => array(
      'title' => 'Financial Problems',
      'nid' => 29182
    ),
 6 => array(
     'title' => 'Abuse',
      'nid' => 29162
    ),
  7 => array(
     'title' => 'Rape',
      'nid' => 29907
    ),
  8 => array(
     'title' => 'Sexual Abuse',
      'nid' => 44617
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
31632 => array(
  'title' => 'Surgery',
  'nid' => 31632,
   'taxonomy' => array(
  0 => array(
      'title' => 'Caregivers',
      'nid' => 44622
    ),
  1 => array(
     'title' => 'Medicare',
      'nid' => 47183
    ),
  2 => array(
   'title' => 'Medicaid',
      'nid' => 47184
    ),
    
   )
 ),
 // End of Item

// Start of item
// Id of the group
31954 => array(
  'title' => 'Teen',
  'nid' => 31954,
   'taxonomy' => array(
  0 => array(
      'title' => 'College',
      'nid' => 29175
    ),
  1 => array(
     'title' => 'Stress',
      'nid' => 29206
    ),
  2 => array(
   'title' => 'Anxiety',
      'nid' => 29168
    ),
  3 => array(
   'title' => 'Depression',
      'nid' => 29176
    ),
4 => array(
    'title' => 'Eating Disorder',
      'nid' => 29179
    ),
   5 => array(
     'title' => 'Family',
      'nid' => 29180
    ),
 6 => array(
     'title' => 'Acne',
      'nid' => 29163
    ),
  7 => array(
     'title' => 'Social Anxiety',
      'nid' => 29168
    ),
  8 => array(
     'title' => 'Self Esteem',
      'nid' => 29932
    ),
  9 => array(
     'title' => 'Self Harm',
      'nid' => 29201
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
35223 => array(
  'title' => 'Testicular Cancer',
  'nid' => 35223,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
     'title' => 'Caregivers',
      'nid' => 44622
    ),
  2 => array(
   'title' => 'Medicare',
      'nid' => 47183
    ),
  3 => array(
   'title' => 'Medicaid',
      'nid' => 47184
    ),
  
   )
 ),
 // End of Item
// Start of item
// Id of the group
35224 => array(
  'title' => 'Thyroid Cancer',
  'nid' => 35224,
   'taxonomy' => array(
  0 => array(
      'title' => 'Chemotherapy',
      'nid' => 37247
    ),
  1 => array(
     'title' => 'Caregivers',
      'nid' => 44622
    ),
  2 => array(
   'title' => 'Medicare',
      'nid' => 47183
    ),
  3 => array(
   'title' => 'Medicaid',
      'nid' => 47184
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
47188 => array(
  'title' => 'Tinnitus',
  'nid' => 47188,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
37231 => array(
  'title' => 'Trazodone',
  'nid' => 37231,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
     'title' => 'Anxiety',
      'nid' => 29168
    ),
   
   )
 ),
 // End of Item


// Start of item
// Id of the group
43573 => array(
  'title' => 'Trichotillomania',
  'nid' => 43573,
   'taxonomy' => array(
  0 => array(
      'title' => 'OCD',
      'nid' => 29194
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
44595 => array(
  'title' => 'Trying To Conceive',
  'nid' => 44595,
   'taxonomy' => array(
  0 => array(
      'title' => 'Endometriosis',
      'nid' => 31428
    ),
  1 => array(
     'title' => 'Pregnancy',
      'nid' => 29903
    ),
  2 => array(
   'title' => 'Infertility',
      'nid' => 29190
    ),
  3 => array(
   'title' => 'Premature Ovarian Failure',
      'nid' => 37214
    ),
4 => array(
    'title' => 'PCOS',
      'nid' => 35206
    ),
   5 => array(
     'title' => 'Moms',
      'nid' => 31952
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
31082 => array(
  'title' => 'Unemployment',
  'nid' => 31082,
   'taxonomy' => array(
  0 => array(
      'title' => 'Career Changes',
      'nid' => 44600
    ),
  1 => array(
     'title' => 'Financial Problems',
      'nid' => 29182
    ),
  2 => array(
   'title' => 'Depression',
      'nid' => 29176
    ),
  3 => array(
   'title' => 'Stress',
      'nid' => 29206
    ),
4 => array(
    'title' => 'Family',
      'nid' => 29180
    ),
    
   )
 ),
 // End of Item

// Start of item
// Id of the group
37232 => array(
  'title' => 'Valium',
  'nid' => 37232,
   'taxonomy' => array(
  0 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  1 => array(
     'title' => 'Panic Attacks',
      'nid' => 29890
    ),
  2 => array(
   'title' => 'Insomnia',
      'nid' => 29192
    ),
  3 => array(
   'title' => 'Social Anxiety',
      'nid' => 29168
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
47185 => array(
  'title' => 'Vegan',
  'nid' => 47185,
   'taxonomy' => array(
  0 => array(
      'title' => 'Nutrition',
      'nid' => 29168
    ),
  1 => array(
     'title' => 'Vegetarian',
      'nid' =>  47186
    ),
  2 => array(
   'title' => 'Healthy Eating',
      'nid' => 35227
    ),
    
   )
 ),
 // End of Item

// Start of item
// Id of the group
47186 => array(
  'title' => 'Vegetarian',
  'nid' => 47186,
   'taxonomy' => array(
  0 => array(
     'title' => 'Healthy Eating',
      'nid' => 35227
    ),
  1 => array(
     'title' => 'Nutrition',
      'nid' => 29168
    ),
  2 => array(
    'title' => 'Vegan',
      'nid' => 47185
    ),
  3 => array(
   'title' => 'Vegan',
      'nid' => 47185
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
52262 => array(
  'title' => 'Veterans',
  'nid' => 52262,
   'taxonomy' => array(
  0 => array(
     'title' => 'PTSD',
      'nid' => 29198
    ),
  1 => array(
     'title' => 'Military Family',
      'nid' => 31436
    ),
  2 => array(
    'title' => 'Career Changes ',
      'nid' => 44600
    ),
  3 => array(
   'title' => 'Stress',
      'nid' => 29206
    ),
4 => array(
    'title' => 'Anxiety',
      'nid' => 29168
    ),
   5 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),
 6 => array(
     'title' => 'War and Terrorism',
      'nid' => 31448
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
37246 => array(
  'title' => 'Vicodin',
  'nid' => 37246,
   'taxonomy' => array(
  0 => array(
     'title' => 'Chronic Pain',
      'nid' => 29901
    ),
  1 => array(
     'title' => 'Drug',
      'nid' => 29027
    ),
  2 => array(
    'title' => 'Prescription Drug',
      'nid' => 29196
    ),
  3 => array(
   'title' => 'Friends and Family of Addicts ',
      'nid' => 29184
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
44608 => array(
  'title' => 'Video Game Addiction',
  'nid' => 44608,
   'taxonomy' => array(
  0 => array(
     'title' => 'Teen',
      'nid' => 31954
    ),
  1 => array(
     'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
   'title' => 'Anxiety',
      'nid' => 29168
    ),
  3 => array(
   'title' => 'Friends and Family of Addicts ',
      'nid' => 29184
    ),
4 => array(
    'title' => 'Loneliness',
      'nid' => 29193
    ),
   5 => array(
     'title' => 'Internet Addiction',
      'nid' => 35211
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
31448 => array(
  'title' => 'War and Terrorism',
  'nid' => 31448,
   'taxonomy' => array(
  0 => array(
     'title' => 'Veterans',
      'nid' => 52262
    ),
  1 => array(
     'title' => 'PTSD',
      'nid' => 29198
    ),
  2 => array(
   'title' => 'Military Family',
      'nid' => 31436
    ),
  3 => array(
   'title' => 'Depression',
      'nid' => 29176
    ),
4 => array(
    'title' => 'Stress',
      'nid' => 29206
    ),
   5 => array(
     'title' => 'Anxiety',
      'nid' => 29168
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
29208 => array(
  'title' => 'Weight Loss',
  'nid' => 29208,
   'taxonomy' => array(
  0 => array(
     'title' => 'Healthy Eating',
      'nid' => 35227
    ),
  1 => array(
     'title' => 'Obesity',
      'nid' => 44618
    ),
  2 => array(
   'title' => 'Diabetes',
      'nid' => 29177
    ),
  3 => array(
   'title' => 'Nutrition',
      'nid' => 44613
    ),
4 => array(
   'title' => 'Depression',
      'nid' => 29176
    ),
   5 => array(
    'title' => 'Self Esteem',
      'nid' => 29932
    ),
   
   )
 ),
 // End of Item

// Start of item
// Id of the group
37236 => array(
  'title' => 'Wellbutrin',
  'nid' => 37236,
   'taxonomy' => array(
  0 => array(
      'title' => 'Depression',
      'nid' => 29176
    ),
  1 => array(
     'title' => 'Loneliness',
      'nid' => 29193
    ),
  2 => array(
   'title' => 'Zoloft',
      'nid' => 37235
    ),
  3 => array(
   'title' => 'Seasonal Affective Disorder',
      'nid' => 52261
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
31985 => array(
  'title' => 'Widow',
  'nid' => 31985,
   'taxonomy' => array(
  0 => array(
      'title' => 'Grief',
      'nid' => 29187
    ),
  1 => array(
       'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
   'title' => 'Loneliness',
      'nid' => 29193
    ),
  
   )
 ),
 // End of Item

// Start of item
// Id of the group
31986 => array(
  'title' => 'Widower',
  'nid' => 31986,
   'taxonomy' => array(
  0 => array(
      'title' => 'Grief',
      'nid' => 29187
    ),
  1 => array(
       'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
   'title' => 'Loneliness',
      'nid' => 29193
    ),  

   )
 ),
 // End of Item
// Start of item
// Id of the group
37233 => array(
  'title' => 'Xanax',
  'nid' => 37233,
   'taxonomy' => array(
  0 => array(
      'title' => 'Anxiety',
      'nid' => 29168
    ),
  1 => array(
       'title' => 'Stress',
      'nid' => 29206
    ),
  2 => array(
   'title' => 'Panic Attack',
      'nid' => 29890
    ),
  3 => array(
   'title' => 'Social Anxiety',
      'nid' => 29168
    ),

   )
 ),
 // End of Item



// Start of item
// Id of the group
37235 => array(
  'title' => 'Zoloft',
  'nid' => 37235,
   'taxonomy' => array(
  0 => array(
      'title' => 'Wellbutrin',
      'nid' => 37236
    ),
  1 => array(
       'title' => 'Depression',
      'nid' => 29176
    ),
  2 => array(
   'title' => 'Loneliness',
      'nid' => 29193
    ),
  3 => array(
   'title' => 'Seasonal Affective Disorder',
      'nid' => 52261
    ),

   )
 ),
 // End of Item


);

return $groupOptions;


}